REM   Script: Trabalho da faculdade comentado
REM   Trabalho da faculdade comentado

CREATE TABLE ALUNOS( 
 Nr_RGM NUMBER (8,0) GENERATED BY DEFAULT AS IDENTITY, 
 Nm_Nomecompleto VARCHAR (40) NOT NULL, 
 Nm_Pai VARCHAR (40), 
 Nm_Mae VARCHAR (40) NOT NULL, 
 Dt_Nascimento DATE, 
 Id_Sexo CHAR (10), 
  
 CONSTRAINT CK_Id_Sexo CHECK (UPPER(Id_Sexo) in ('M', 'F', 'OUTROS')), 
 PRIMARY KEY (Nr_RGM) 
  
 -- Usei 'GENERATED BY DEFAULT AS IDENTITY' que a partir do Oracle 12c , foi introduzido para criar automaticamente numeros de formas sequenciais. Ele equivale o "AutoIncrement" do MYSQL. 
 -- Nas versões anteriores, outra forma de criar sequencias de numeros era atraves do "Sequence" Aula no link: https://www.youtube.com/watch?v=_7XNfW7oMxQ 
 -- A cod consiste em: GENERATED [ ALWAYS | BY DEFAULT [ ON NULL ] ] AS IDENTITY [ ( identity_options ) ]  
 -- Usei como fonte o link https://www.oracletutorial.com/oracle-basics/oracle-identity-column/#:~:text=GENERATED%20BY%20DEFAULT%20%3A%20Oracle%20generates,value%20into%20the%20identity%20column. 
 );

 CREATE TABLE CLASSE( 
 Cd_Classe NUMBER (8,0) GENERATED BY DEFAULT AS IDENTITY, 
 Nr_AnoLetivo NUMBER (4,0) NOT NULL, 
 NR_Serie NUMBER (2,0) NOT NULL, 
 SG_Turma VARCHAR2 (2) NOT NULL, 
 Cd_Escola NUMBER (6,0) NOT NULL, 
 Cd_Grau NUMBER (1,0) NOT NULL, 
 Cd_Periodo NUMBER (2,0) NOT NULL, 
  PRIMARY KEY (Cd_Classe)  
 );

 CREATE TABLE MATRICULA( 
 Nr_RGM NUMBER (8,0), 
 Cd_Classe NUMBER (8,0), 
 Dt_matricula DATE, 
  
 CONSTRAINT MATRICULA_pk PRIMARY KEY (Nr_RGM,Cd_Classe), 
 CONSTRAINT Nr_RGM_fk FOREIGN KEY (Nr_RGM) REFERENCES ALUNOS (Nr_RGM), 
 CONSTRAINT Classe_fk FOREIGN KEY (Cd_Classe) REFERENCES CLASSE (Cd_Classe) 
 );

